# Generated by Django 3.2.11 on 2022-05-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220526_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='country',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(default='', max_length=21),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='postalcode',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='town',
            field=models.CharField(default='', max_length=56),
        ),
    ]
