# Generated by Django 3.2.11 on 2022-02-20 18:37

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('describe', ckeditor.fields.RichTextField()),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Discount Price')),
                ('discount_text', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_active', models.BooleanField(default=False)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.ImageField(upload_to='giftshop/')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
