# Generated by Django 3.2.11 on 2022-03-28 04:20

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Discount Price')),
                ('discount_text', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_active', models.BooleanField(default=False)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ecard', models.FileField(upload_to='giftshop/ecard/')),
            ],
        ),
        migrations.RenameField(
            model_name='giftshop',
            old_name='describe',
            new_name='description',
        ),
    ]
