# Generated by Django 3.2.11 on 2022-02-13 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0002_auto_20220213_2053'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[(1, 'Available'), (2, 'Sold'), (3, 'Reserved')], default=1, max_length=30)),
                ('order_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(default='', max_length=21)),
                ('address', models.CharField(default='', max_length=256)),
                ('town', models.CharField(default='', max_length=56)),
                ('postalcode', models.CharField(default='', max_length=11)),
                ('country', models.CharField(default='', max_length=250)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('include_gift', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ticket', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('ticket_name', models.CharField(default='', max_length=4, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='cart.order')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.competitionticket')),
            ],
        ),
    ]
