# Generated by Django 3.2.11 on 2022-02-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Active'), (2, 'Sold'), (3, 'Reserved')], default=1, max_length=30),
        ),
    ]
