# Generated by Django 3.2.11 on 2022-05-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftshop', '0002_auto_20220328_0920'),
        ('competitions', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ticket_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='title',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='giftshop.giftshop'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Active'), (2, 'Cart'), (3, 'Delivered')], default=2, max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.competitionticket'),
        ),
    ]
