# Generated by Django 3.2.11 on 2022-05-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220524_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Cart'), (3, 'Delivered')], default=2, max_length=30),
        ),
    ]
