# Generated by Django 3.2.11 on 2022-06-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_cartitem_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cart_image'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='title',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
