# Generated by Django 3.2.11 on 2022-06-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20220601_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
