# Generated by Django 3.2.11 on 2022-06-01 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_cartitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='image',
        ),
    ]
