# Generated by Django 3.2.11 on 2022-06-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_remove_cartitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Price'),
        ),
    ]
