# Generated by Django 3.2.11 on 2022-02-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competition_date_reschedual',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='coupon_code_asked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='discount_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='live_draw_link',
            field=models.URLField(blank=True, default='https://google.com/', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='total_earned',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='ultimate_closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
